### ISSUE TITLE
Erratic "Error in handler" when trying to view an image 

### ISSUE THREAD

**Issue by dprov** [elazarcoh/simply-view-image-for-python-debugging#85] opened 2024-02-28 14:33 UTC
I've been using the extension for some time (**great** work by the way!), but recently noticed that viewing images has been working erratically. Sometimes it seems to work fine, some other times I have erratic behavior as follows:
- If the "Image View" window is closed, clicking on "View image" in the Image watch generally does not open it. Sometimes spamming that button ends up working.
- If the "Image View" window is open, images do not update
![image](https://github.com/elazarcoh/simply-view-image-for-python-debugging/assets/46375825/a5f0e3ff-3aa5-41a6-9fd3-fca02284ca9b)

After some testing to make a minimal example, with the following
````
import numpy as np

np.random.seed(0) # problematic
 
if __name__ == "__main__":
    im = np.random.randint(0, 255, (20, 20), dtype=np.uint8)
    a = 1 # breakpoint on this line
````
Without "np.random.seed(0)" it works without issues
With "np.random.seed(0)", I have the erratic behavior. Trying to display an image yields the following output (verbose mode)
<details>
  <summary>Output</summary>

````
"[Debug]" "Sending code to python: " {
  "pythonCode": "_python_view_image_mod.eval_into_value(lambda: _python_view_image_mod.open_send_and_close(49628, 2542223483, im))"
}
"[Debug]" "Sending request to python with reqId " 2542223483
"[Trace]" "onWillReceiveMessage" {
  "command": "evaluate",
  "arguments": {
    "expression": "_python_view_image_mod.stringify(_python_view_image_mod.eval_into_value(lambda: _python_view_image_mod.open_send_and_close(49628, 2542223483, im)))",
    "frameId": 2,
    "context": "repl"
  },
  "type": "request",
  "seq": 28
}
"[Trace]" "Received %d bytes from client" 461
"[Trace]" "Parsed header" {
  "messageLength": 435,
  "messageID": 1883779156,
  "sender": 2,
  "requestId": 2542223483,
  "messageType": 1,
  "chunkCount": 1,
  "chunkNumber": 0,
  "chunkLength": 435
}
"[Debug]" "Error in handler"
"[Debug]" {}
"[Trace]" "Client ended connection"
"[Trace]" "onDidSendMessage" {
  "seq": 36,
  "type": "response",
  "request_seq": 28,
  "success": true,
  "command": "evaluate",
  "body": {
    "result": "'Value(None)'",
    "variablesReference": 0,
    "type": "str",
    "presentationHint": {
      "attributes": [
        "rawString"
      ]
    }
  }
}
````

</details>

More info: 
- version v3.0.19 (pre-release)
- Tried with/without Experimental data transfer

**Comment by elazarcoh** [comment] 2024-02-28 18:46
Hi,
Thanks for raising it! 
I'm noticing a bug in the log, which is why I can't see the actual error. I'll try to push a new version soon, so we can debug it with more information. 
(needless to say, I can't reproduce it, though it's believable there are quite a few bugs in my implementation).

**Comment by elazarcoh** [comment] 2024-02-28 19:17
Just updated to version 3.0.21 pre-release with fixed logging. Please update the attach the new log with the info.

**Comment by dprov** [comment] 2024-02-28 21:11
Here it is: 
<details><summary>Output</summary>

````
"[Debug]" "Sending code to python: " {
  "pythonCode": "_python_view_image_mod.eval_into_value(lambda: _python_view_image_mod.open_send_and_close(56841, 1981716379, im))"
}
"[Debug]" "Sending request to python with reqId " 1981716379
"[Trace]" "onWillReceiveMessage" {
  "command": "evaluate",
  "arguments": {
    "expression": "_python_view_image_mod.stringify(_python_view_image_mod.eval_into_value(lambda: _python_view_image_mod.open_send_and_close(56841, 1981716379, im)))",
    "frameId": 2,
    "context": "repl"
  },
  "type": "request",
  "seq": 27
}
"[Trace]" "Received %d bytes from client" 461
"[Trace]" "Parsed header" {
  "messageLength": 435,
  "messageID": 1883779156,
  "sender": 2,
  "requestId": 1981716379,
  "messageType": 1,
  "chunkCount": 1,
  "chunkNumber": 0,
  "chunkLength": 435
}
"[Debug]" "Error in handler"
"[Debug]" {
  "stack": "Error: Chunk number 0 already exists\n\tat t.MessageChunks.addChunk (c:\\Users\\dprovencher\\.vscode\\extensions\\elazarcoh.simply-view-image-for-python-debugging-3.0.21\\dist\\extension.js:2:100626)\n\tat i (c:\\Users\\dprovencher\\.vscode\\extensions\\elazarcoh.simply-view-image-for-python-debugging-3.0.21\\dist\\extension.js:2:104635)\n\tat Socket.<anonymous> (c:\\Users\\dprovencher\\.vscode\\extensions\\elazarcoh.simply-view-image-for-python-debugging-3.0.21\\dist\\extension.js:2:104750)\n\tat Socket.emit (node:events:514:28)\n\tat addChunk (node:internal/streams/readable:324:12)\n\tat readableAddChunk (node:internal/streams/readable:297:9)\n\tat Socket.push (node:internal/streams/readable:234:10)\n\tat TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
  "message": "Chunk number 0 already exists"
}
"[Trace]" "Client ended connection"
"[Trace]" "onDidSendMessage" {
  "seq": 35,
  "type": "response",
  "request_seq": 27,
  "success": true,
  "command": "evaluate",
  "body": {
    "result": "'Value(None)'",
    "variablesReference": 0,
    "type": "str",
    "presentationHint": {
      "attributes": [
        "rawString"
      ]
    }
  }
}
````

</details>

**Comment by elazarcoh** [comment] 2024-02-29 09:13
Thanks, that is helpful. I'll look into it soon.

**Comment by dprov** [comment] 2024-02-29 18:43
There you go.
<details><summary>Output</summary>

````
"[Debug]" "Sending code to python: " {
  "pythonCode": "_python_view_image_mod.eval_into_value(lambda: _python_view_image_mod.open_send_and_close(51686, 2377569439, im))"
}
"[Debug]" "Sending request to python with reqId " 2377569439
"[Trace]" "onWillReceiveMessage" {
  "command": "evaluate",
  "arguments": {
    "expression": "_python_view_image_mod.stringify(_python_view_image_mod.eval_into_value(lambda: _python_view_image_mod.open_send_and_close(51686, 2377569439, im)))",
    "frameId": 2,
    "context": "repl"
  },
  "type": "request",
  "seq": 23
}
"[Trace]" "Received 461 bytes from client"
"[Trace]" "Parsed header" {
  "messageLength": 435,
  "messageID": 1883779156,
  "sender": 2,
  "requestId": 2377569439,
  "messageType": 1,
  "chunkCount": 1,
  "chunkNumber": 0,
  "chunkLength": 435
}
"[Debug]" "Error in handler"
"[Debug]" {
  "stack": "Error: Chunk number 0 already exists. current: {\"messageLength\":435,\"messageID\":1883779156,\"sender\":2,\"requestId\":2109206472,\"messageType\":1,\"chunkCount\":1,\"chunkNumber\":0,\"chunkLength\":435}\n\tat t.MessageChunks.addChunk (c:\\Users\\dprovencher\\.vscode\\extensions\\elazarcoh.simply-view-image-for-python-debugging-3.0.22\\dist\\extension.js:2:100700)\n\tat i (c:\\Users\\dprovencher\\.vscode\\extensions\\elazarcoh.simply-view-image-for-python-debugging-3.0.22\\dist\\extension.js:2:104962)\n\tat Socket.<anonymous> (c:\\Users\\dprovencher\\.vscode\\extensions\\elazarcoh.simply-view-image-for-python-debugging-3.0.22\\dist\\extension.js:2:105077)\n\tat Socket.emit (node:events:514:28)\n\tat addChunk (node:internal/streams/readable:324:12)\n\tat readableAddChunk (node:internal/streams/readable:297:9)\n\tat Socket.push (node:internal/streams/readable:234:10)\n\tat TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
  "message": "Chunk number 0 already exists. current: {\"messageLength\":435,\"messageID\":1883779156,\"sender\":2,\"requestId\":2109206472,\"messageType\":1,\"chunkCount\":1,\"chunkNumber\":0,\"chunkLength\":435}"
}
"[Trace]" "Client ended connection"
"[Trace]" "onDidSendMessage" {
  "seq": 35,
  "type": "response",
  "request_seq": 23,
  "success": true,
  "command": "evaluate",
  "body": {
    "result": "'Value(None)'",
    "variablesReference": 0,
    "type": "str",
    "presentationHint": {
      "attributes": [
        "rawString"
      ]
    }
  }
}
````

</details> 

In case it helps, I tested with a fresh environment
``conda create --name test_im_viewer python=3.11.6  numpy=1.26.0 -c conda-forge``

As before, I don't have issues without the random seed line, but it seems to trigger about 1/2 the time when I put it in, for whatever obscure reason.
It's most obvious if I close the Image View window every time, then I know for sure when trying to open it does not work as opposed to wondering if the image in the viewer ended up being updated or not.

**Comment by elazarcoh** [comment] 2024-02-29 19:09
The log now is very helpful.  I can see the server got the same message twice for some reason. 
Please install this version and see if it works now.
https://github.com/elazarcoh/simply-view-image-for-python-debugging/blob/0452f4db057a9542694a81b6214c3801cf73dee5/simply-view-image-for-python-debugging-3.0.23.vsix
Even if it does, please attach the log, I would like to confirm the it.

**Comment by dprov** [comment] 2024-02-29 20:09
Still no luck:

<details><summary>Output</summary>

```` 
"[Debug]" "Sending code to python: " {
  "pythonCode": "_python_view_image_mod.eval_into_value(lambda: _python_view_image_mod.open_send_and_close(54038, 3029328853, im))"
}
"[Debug]" "Sending request to python with reqId " 3029328853
"[Trace]" "onWillReceiveMessage" {
  "command": "evaluate",
  "arguments": {
    "expression": "_python_view_image_mod.stringify(_python_view_image_mod.eval_into_value(lambda: _python_view_image_mod.open_send_and_close(54038, 3029328853, im)))",
    "frameId": 2,
    "context": "repl"
  },
  "type": "request",
  "seq": 23
}
"[Trace]" "Received 461 bytes from client"
"[Trace]" "Parsed header" {
  "messageLength": 435,
  "messageID": 1883779156,
  "sender": 2,
  "requestId": 3029328853,
  "messageType": 1,
  "chunkCount": 1,
  "chunkNumber": 0,
  "chunkLength": 435
}
"[Debug]" "Error in handler"
"[Debug]" {
  "stack": "Error: (reqId 3029328853) Chunk number 0 already exists. current: {\"messageLength\":435,\"messageID\":1883779156,\"sender\":2,\"requestId\":3152398677,\"messageType\":1,\"chunkCount\":1,\"chunkNumber\":0,\"chunkLength\":435}\n\tat t.MessageChunks.addChunk (c:\\Users\\dprovencher\\.vscode\\extensions\\elazarcoh.simply-view-image-for-python-debugging-3.0.23\\dist\\extension.js:2:101024)\n\tat i (c:\\Users\\dprovencher\\.vscode\\extensions\\elazarcoh.simply-view-image-for-python-debugging-3.0.23\\dist\\extension.js:2:105574)\n\tat Socket.<anonymous> (c:\\Users\\dprovencher\\.vscode\\extensions\\elazarcoh.simply-view-image-for-python-debugging-3.0.23\\dist\\extension.js:2:105689)\n\tat Socket.emit (node:events:514:28)\n\tat addChunk (node:internal/streams/readable:324:12)\n\tat readableAddChunk (node:internal/streams/readable:297:9)\n\tat Socket.push (node:internal/streams/readable:234:10)\n\tat TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
  "message": "(reqId 3029328853) Chunk number 0 already exists. current: {\"messageLength\":435,\"messageID\":1883779156,\"sender\":2,\"requestId\":3152398677,\"messageType\":1,\"chunkCount\":1,\"chunkNumber\":0,\"chunkLength\":435}"
}
"[Trace]" "Client ended connection"
"[Trace]" "onDidSendMessage" {
  "seq": 35,
  "type": "response",
  "request_seq": 23,
  "success": true,
  "command": "evaluate",
  "body": {
    "result": "'Value(None)'",
    "variablesReference": 0,
    "type": "str",
    "presentationHint": {
      "attributes": [
        "rawString"
      ]
    }
  }
}
```` 

</details>

**Comment by elazarcoh** [comment] 2024-02-29 20:25
Oh I see now it's not the same requestId. Hmm... More debugging is needed.
Thanks

**Comment by elazarcoh** [comment] 2024-02-29 21:08
Care for another round?
https://github.com/elazarcoh/simply-view-image-for-python-debugging/blob/b6f99b43e5e9b4fd5aaa808a98b970a978334d57/simply-view-image-for-python-debugging-3.0.24.vsix
Figured that I'm using `np.random`. replaced with with a RandomGenerator object instead.

**Comment by dprov** [comment] 2024-02-29 21:52
It works, yay!
I'm glad the fix was so simple after all (although it must have been a pain to track...)

Thanks for the help!

**Comment by elazarcoh** [comment] 2024-02-29 21:58
Thank you for helping me figure it out!

I'll try to make a (pre-) release tomorrow or next week. It'll be version 3.0.23 so make sure to reinstall it (not sure it will be installed automatically because the version I sent you, I numbered it 3.0.24)

**Closed** 2024-03-04 18:56 UTC
